name: Generate Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Generate Report
      run: |
        python generate_report.py
    - name: Commit and Push
      run: |
        git config --global user.email "hoangthanh1367@gmail.com"
        git config --global user.name "hoangthanh168"
        git add report.md
        git commit -m "Update weekly report"
        git push
